import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../modules/layout/components/navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <Navbar />
        <section className="content-container my-4 flex flex-col gap-4">
          {children}
        </section>
      </body>
    </html>
  );
}
